apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - agent-config.yaml
  - external-secrets.yaml
  - validator-origin.yaml
  - validator-target.yaml
  - relayer.yaml
  - relayer-service.yaml
  - relayer-ingress.yaml
