apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: hyperlane
data:
  agent-config.json: |-
    {
      "chains": {
        "bullettestnet": {
          "name": "bullettestnet",
          "displayName": "Bullet Testnet",
          "isTestnet": true,
          "index": {
            "chunk": 100
          },
          "domainId": "5556",
          "protocol": "sovereign",
          "rpcUrls": [{ "http": "http://rollup.applications" }],
          "mailbox": "0x0000000000000000000000000000000000000000",
          "interchainGasPaymaster": "0x0000000000000000000000000000000000000000",
          "validatorAnnounce": "0x0000000000000000000000000000000000000000",
          "domainRoutingIsmFactory": "0x0000000000000000000000000000000000000000",
          "interchainAccountIsm": "0x0000000000000000000000000000000000000000",
          "interchainAccountRouter": "0x0000000000000000000000000000000000000000",
          "proxyAdmin": "0x0000000000000000000000000000000000000000",
          "staticAggregationHookFactory": "0x0000000000000000000000000000000000000000",
          "staticAggregationIsmFactory": "0x0000000000000000000000000000000000000000",
          "staticMerkleRootMultisigIsmFactory": "0x0000000000000000000000000000000000000000",
          "staticMerkleRootWeightedMultisigIsmFactory": "0x0000000000000000000000000000000000000000",
          "staticMessageIdMultisigIsmFactory": "0x0000000000000000000000000000000000000000",
          "staticMessageIdWeightedMultisigIsmFactory": "0x0000000000000000000000000000000000000000",
          "testRecipient": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "merkleTreeHook": "0x0000000000000000000000000000000000000000",
          "signer": {
            "type": "sovereignKey",
            "accountType": "solana"
          },
          "finalityBlocks": 1
        }
      },
      "blacklist": []
    }
