apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-rpc
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-rpc
    creationPolicy: Owner
  data:
    - secretKey: validator_rpc
      remoteRef:
        key: /unmanaged/secrets/hyperlane/validator_rpc
    - secretKey: relayer_rpc
      remoteRef:
        key: /unmanaged/secrets/hyperlane/relayer_rpc
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-validator-solanamainnet-secrets
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-validator-solanamainnet-secrets
    creationPolicy: Owner
  data:
    - secretKey: hyperlane_validator_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/validator_signer_key
    - secretKey: origin_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/solana_signer_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-validator-bulletmainnet-secrets
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-validator-bulletmainnet-secrets
    creationPolicy: Owner
  data:
    - secretKey: hyperlane_validator_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/validator_signer_key
    - secretKey: origin_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/bullet_signer_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-relayer-secrets
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-relayer-secrets
    creationPolicy: Owner
  data:
    - secretKey: target_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/bullet_signer_key
    - secretKey: origin_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/solana_signer_key
