apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hyperlane-relayer
  namespace: hyperlane
spec:
  replicas: 1
  serviceName: hyperlane-relayer
  selector:
    matchLabels:
      app: hyperlane-relayer
  template:
    metadata:
      labels:
        app: hyperlane-relayer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      serviceAccountName: default
      containers:
        - name: hyperlane-relayer
          image: 840153641671.dkr.ecr.ap-northeast-1.amazonaws.com/hyperlane:latest
          env:
            - name: CONFIG_FILES
              value: "/configs/agent-config.json"
            - name: HYP_CHAINS_BULLETMAINNET_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-relayer-secrets
                  key: target_chain_signer_key
            - name: HYP_CHAINS_SOLANAMAINNET_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-relayer-secrets
                  key: origin_chain_signer_key
            - name: ORIGIN_CHAIN_RPC_URL_RELAYER
              valueFrom:
                secretKeyRef:
                  name: hyperlane-rpc
                  key: relayer_rpc
          ports:
            - containerPort: 9091
            - containerPort: 9090
          volumeMounts:
            - name: agent-config
              mountPath: /configs/agent-config.json
              subPath: agent-config.json
              readOnly: true
            - name: hyperlane-db
              mountPath: /hyperlane_db
          command: ["./relayer"]
          args:
            - "--db"
            - "/hyperlane_db"
            - "--relayChains"
            - "bulletmainnet,solanamainnet"
            - "--metrics-port"
            - "9091"
            - "--gasPaymentEnforcement"
            - '[{"type":"none"}]'
            - "--whitelist"
            - '[{"destinationDomain":"5555"},{"destinationDomain":"1399811149"}]'
            - "--chains.solanamainnet.customRpcUrls"
            - "$(ORIGIN_CHAIN_RPC_URL_RELAYER)"
            - "--chains.solanamainnet.index.from"
            - "353202"
            - "--log.format"
            - "json"
            - "--log.level"
            - "debug"
          resources:
            requests:
              memory: "5Gi"
              cpu: "500m"
            limits:
              memory: "12Gi"
              cpu: "2000m"
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
            items:
              - key: agent-config.json
                path: agent-config.json
  volumeClaimTemplates:
  - metadata:
      name: hyperlane-db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp3
