apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hyperlane-validator-solanamainnet
  namespace: hyperlane
spec:
  replicas: 1
  serviceName: hyperlane-validator-solanamainnet
  selector:
    matchLabels:
      app: hyperlane-validator-solanamainnet
  template:
    metadata:
      labels:
        app: hyperlane-validator-solanamainnet
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: '/metrics'
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      serviceAccountName: validator-solanamainnet-mainnet
      containers:
        - name: hyperlane-validator-solanamainnet
          image: 840153641671.dkr.ecr.ap-northeast-1.amazonaws.com/hyperlane:latest
          env:
            - name: CONFIG_FILES
              value: '/configs/agent-config.json'
            - name: HYP_VALIDATOR_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-validator-solanamainnet-secrets
                  key: hyperlane_validator_signer_key
            - name: HYP_CHAINS_SOLANAMAINNET_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-validator-solanamainnet-secrets
                  key: origin_chain_signer_key
            - name: ORIGIN_CHAIN_RPC_URL_VALIDATOR
              valueFrom:
                secretKeyRef:
                  name: hyperlane-rpc
                  key: validator_rpc
          volumeMounts:
            - name: agent-config
              mountPath: /configs/agent-config.json
              subPath: agent-config.json
              readOnly: true
            - name: hyperlane-db
              mountPath: /hyperlane_db
          command: ['./validator']
          args:
            - '--db'
            - '/hyperlane_db'
            - '--originChainName'
            - 'solanamainnet'
            - '--chains.solanamainnet.customRpcUrls'
            - '$(ORIGIN_CHAIN_RPC_URL_VALIDATOR)'
            - '--checkpointSyncer.type'
            - 's3'
            - '--checkpointSyncer.bucket'
            - 'hyperlane-validator-mainnet-bucket'
            - '--checkpointSyncer.region'
            - 'ap-northeast-1'
            - '--checkpointSyncer.folder'
            - 'solanamainnet-signatures'
            - '--log.format'
            - 'json'
            - '--log.level'
            - 'debug'
            - '--metrics-port'
            - '9090'
          ports:
            - containerPort: 9090
              name: metrics
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '8Gi'
              cpu: '2000m'
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
            items:
              - key: agent-config.json
                path: agent-config.json
  volumeClaimTemplates:
    - metadata:
        name: hyperlane-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp3
