apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hyperlane-validator-bulletmainnet
  namespace: hyperlane
spec:
  replicas: 1
  serviceName: hyperlane-validator-bulletmainnet
  selector:
    matchLabels:
      app: hyperlane-validator-bulletmainnet
  template:
    metadata:
      labels:
        app: hyperlane-validator-bulletmainnet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      serviceAccountName: validator-bulletmainnet-mainnet
      containers:
        - name: hyperlane-validator-bulletmainnet
          image: 840153641671.dkr.ecr.ap-northeast-1.amazonaws.com/hyperlane:latest
          env:
            - name: CONFIG_FILES
              value: "/configs/agent-config.json"
            - name: HYP_VALIDATOR_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-validator-bulletmainnet-secrets
                  key: hyperlane_validator_signer_key
            - name: HYP_CHAINS_BULLETMAINNET_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperlane-validator-bulletmainnet-secrets
                  key: origin_chain_signer_key
          volumeMounts:
            - name: agent-config
              mountPath: /configs/agent-config.json
              subPath: agent-config.json
              readOnly: true
            - name: hyperlane-db
              mountPath: /hyperlane_db
          command: ["./validator"]
          args:
            - "--db"
            - "/hyperlane_db"
            - "--originChainName"
            - "bulletmainnet"
            - "--chains.bulletmainnet.customRpcUrls"
            - "http://rollup.applications"
            - "--checkpointSyncer.type"
            - "s3"
            - "--checkpointSyncer.bucket"
            - "hyperlane-validator-mainnet-bucket"
            - "--checkpointSyncer.region"
            - "ap-northeast-1"
            - "--checkpointSyncer.folder"
            - "bulletmainnet-signatures"
            - "--log.format"
            - "json"
            - "--log.level"
            - "debug"
            - "--metrics-port"
            - "9090"
          ports:
            - containerPort: 9090
              name: metrics
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "2000m"
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
            items:
              - key: agent-config.json
                path: agent-config.json
  volumeClaimTemplates:
  - metadata:
      name: hyperlane-db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp3
